### ISSUE TITLE
genomehubs index --file-metadata should check existing files

### ISSUE THREAD

**Issue by sujaikumar** [genomehubs/genomehubs#142]
Currently:
```
genomehubs index --taxonomy-source ncbi --config-file goat.yaml --file-metadata btk/btk.files.yaml
```
indexes all files in btk.files.yaml and puts them in config --hub-path/files

It would be useful to check if the file to be indexed already exists in the expected location so it does not have to be downloaded again.

**Comment by rjchallis** [comment]
I've been looking at this while dealing with #91 and #131, but this looks harder to implement than I first thought. The problem is that for remote files, the file metadata is extracted from a temporary local copy of the file, so after the import is complete all that is available on disk is the preview image. The file metadata could be queried from the previous index version but then the import code needs to query all existing files and check on disk for the preview images. And this is without considering whether the source file may have changed.

I think a better approach for regular Goat updates will be to modify the import process rather than the code. Given that we expect the files to remain the same between imports, we can copy the previous index to the new version, then import only those entries that have been added since the previous import. Then we can run the full import much less frequently to refresh the index and pick up any file changes.
