### ISSUE TITLE
Filling of homonyms on GoaT propagates wrong estimates

### ISSUE THREAD

**Issue by ccaio** [genomehubs/genomehubs#147]
Melanotus sp. can refer to a fungi or beetle (Coleoptera) species. There is no Melanotus sp. as a Coleoptera on NCBI taxonomy, but there are multiple fungi Melanotus sp. (taxon IDs - 2659796, 2659797, 2659798, 2282672, 2282677, 2282691, 2282667). GoaT is filling the fungi Melanotus sp. karyotype attributes with data from the Coleoptera database and propagating it across fungi instead of throwing the the entry to the exceptions file.

Taxon record here:
[https://goat.genomehubs.org/records?record_id=2041008&result=taxon&taxonomy=ncbi#Melanotus%20sp.%20(in%3A%20Fungi)](url)

Source file here:
[https://github.com/genomehubs/goat-data/blob/main/sources/genomesize_karyotype/coleo-2021-07-28.csv](url)

**Comment by rjchallis** [comment]
The taxon id lookup was not accounting for lineage. I've created a branch that fixes this problem by using a strict lineage lookup, but that will lead to more exceptions due to the use of synonyms for higher taxonomic levels. I'll make a PR to link it here but still need to add a further step to check synonyms if the scientific name for a higher rank in the taxonomy section does not match exactly.

**Comment by rjchallis** [comment]
I've relaxed the lineage lookup to include ancestral synonyms. The number of ancestral ranks to check is controlled by a `--taxon-lineage-matches` flag (default 2), which is the minimum number of consecutive ranks defined in the taxonomy section that must match, starting from the lowest defined rank above species. If fewer ranks are defined, all must match.
