### ISSUE TITLE
ERROR 2005

### ISSUE THREAD

**Issue by jhagberg** [genomehubs/genomehubs#6]
Hej I am following your guide to release 89

and when running the database.sh script in a genomehubs/easy-mirror Docker container:
I get tons of the following error.

```mysqlimport: Error: 2005 Unknown MySQL server host '172.17.0.0/255.255.0.0' (0)```

What can I do to fix this. 

And btw when are you supporting release 90?

**Comment by rjchallis** [comment]
Thanks for reporting the issue.

I can reproduce this and think I see what needs to be fixed: it looks like the script is using a host range, rather than a single IP for the -h flag in a mysqlimport command as it is filling in the value of the wrong variable. I don't want to rush to fix this as I need to work out how we have sites running the same code successfully before I commit a fix.

Meanwhile you can get past this error by changing a line in the database.ini file to 
```
DB_IMPORT_HOST = genomehubs-mysql
```
but the host range should be used in a MySQL `CREATE USER` command so you may run into other database connection problems until I get the container image updated.

I'm afraid we won't be supporting Ensembl 90 - we don't have the resources for this project to keep on top of every Ensembl release so (as with the gap between versions 85 and 89 that are available now) we aim to add support for a new version every 9-12 months.

**Comment by rjchallis** [comment]
I've updated the Docker image to fix this bug. If you run `docker pull genomehubs/easy-mirror:17.06` to make sure you have the latest version then you should be able to carry on following the guide.
