### ISSUE TITLE
v93 importing interproscan

### ISSUE THREAD

**Issue by IainPerry** [genomehubs/genomehubs#8]
Running through with example data.  Having generated and check interpro and blastp we tried to import analysis.  Importing gave this error:

Use of uninitialized value $transcript_id in concatenation (.) or string at /ensembl/easy-import/core/../modules/EasyImport/Xref.pm line 419, <> line 1.
DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND ensembl_object_type LIKE 'Translation' AND analysis_id = 3 AND xref_id = 1' at line 1 at /ensembl/easy-import/core/../modules/EasyImport/Xref.pm line 420, <> line 1.
Use of uninitialized value $transcript_id in concatenation (.) or string at /ensembl/easy-import/core/../modules/EasyImport/Xref.pm line 425, <> line 1.
DBD::mysql::db do failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''Translation',3)' at line 2 at /ensembl/easy-import/core/../modules/EasyImport/Xref.pm line 425, <> line 1.
DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND ensembl_object_type LIKE 'Translation' AND analysis_id = 3 AND xref_id = 1' at line 1 at /ensembl/easy-import/core/../modules/EasyImport/Xref.pm line 431, <> line 1.
DBD::mysql::st fetchrow_arrayref failed: fetch() without execute() at /ensembl/easy-import/core/../modules/EasyImport/Xref.pm line 432, <> line 1.
Can't use an undefined value as an ARRAY reference at /ensembl/easy-import/core/../modules/EasyImport/Xref.pm line 432, <> line 1.
cp: cannot stat '/import/download/Operophtera_brumata_Obru1/interproscan/Operophtera_brumata_Obru1.proteins.fa.interproscan.tsv.gz': No such file or directory
ERROR: could not cp /import/download/Operophtera_brumata_Obru1/interproscan/Operophtera_brumata_Obru1.proteins.fa.interproscan.tsv.gz to Operophtera_brumata_Obru1.proteins.fa.interproscan.tsv.gz

**Comment by rjchallis** [comment]
Sorry you've hit an error - the upgrade to v93 got interrupted by other projects so I'm afraid I haven't managed to get the analysis imports fully tested yet.  I've been trying to clear a couple of weeks to focus on making sure this is all working smoothly and I'm planning to get started next week - so your issue has come just in time for me to add another thing to test.

I'll be sure to comment back here once things are fully checked.  If you want to try GenomeHubs out more fully in the meantime, you should be able to get further by following the v89 instructions using the tabs at the top of the gitbook to switch versions.

If you've encountered any other issues getting this far, please do let me know and I can try to get them fixed as I go.

**Comment by IainPerry** [comment]
We'll have a play through v89. I think a few of the issues stem from scripts giving different output names than required in the next steps.. eg Operophtera_brumata_Obru1_proteins.fa vs Operophtera_brumata_Obru1.proteins.fa.gz. We tried doing these changes manually like copying data from v1/blast/data to v1/download/data/sequence but feel like it ends up causing more problems down the line. We found Easyimporter with the "-u" tag cant find the perl script to run. in the checking of the import of the test data the log file is ~/genomehubs/v1/import/data/operophtera_brumata_obru1_core_40_93_1/log rather than /logs

It is also worth noting that the repeat library is now behind a high cost paywall and perhaps another repeat masker would be worth offering as an option e.g. nextgenusfs/redmask which doesn't require an existing library download. Especially useful for us that work in creepy crawlies and not highly researched mammals. 

Its a great resource though, so thank you for working so hard on it!!

**Comment by rjchallis** [comment]
Thanks for the details. Good to have a few targets to start fixing.

**Comment by rjchallis** [comment]
I've been through all the instructions and containers and I think it should all be working now. Most containers/repositories now have a 19.05 release which is the one shown in the updated docs and the one to use if available.

File locations have been moved since previous versions so now most downloadable file types are grouped by assembly - everything should be looking in consistent locations again so the imports should be fine.

The script for the `-u` import tag was in a dev branch so I've copied that across.

And I've added a redmask container, that doesn't generate a classified output like repeat masker but does give masked genome versions.

Hope your genome databasing goes well and do let me know if you find more bugs or have suggestions for making the docs easier to follow.

**Comment by IainPerry** [comment]
Having a go with 19.05. Just run:docker run --rm -u 0:0 --name easy-import-operophtera_brumata_v1_core_40_93_1 --network genomehubs-network -v ~/genomehubs/v1/import/conf:/import/conf -v ~/genomehubs/v1/import/data:/import/data -e DATABASE=operophtera_brumata_obru1_core_40_93_1 -e FLAGS="-s -p -g -v" genomehubs/easy-import:19.05

have the error after it saves the files:
2019-05-18 10:22:14 (18.0 MB/s) - 'ObruPep.fasta.gz' saved [3875142/3875142]

cp: cannot stat 'fa': No such file or directory
ERROR: could not cp fa to fa
preparing gff
cp: cannot stat 'fa': No such file or directory
ERROR: could not cp fa to fa
importing gene models
cp: cannot stat 'fa': No such file or directory
ERROR: could not cp fa to fa
verifying import
DBD::mysql::st execute failed: Table 'genus_species_asm_core_40_93_1.meta' doesn't exist at /ensembl/ensembl/modules/Bio/EnsEMBL/DBSQL/BaseMetaContainer.pm line 140, <INI> line 95.
DBD::mysql::st execute failed: Table 'genus_species_asm_core_40_93_1.meta' doesn't exist at /ensembl/ensembl/modules/Bio/EnsEMBL/DBSQL/BaseMetaContainer.pm line 140, <INI> line 95.
cat: summary/verify_translations.log: No such file or directory

will have another try Monday encase its an issue my end.

**Comment by IainPerry** [comment]
Hi thanks for going through all of this. I'm almost at a working interface but for a few issues that might be hardcoded in the docker containers.
http://localhost:8881/Operophtera_brumata_obru1/Info/Index does not display the assembly or codon usage. 
When I inspect element it suggests it is looking for http://download.genomehubs.org/html/codon-usage/codon-usage.html?path=/v1/json/annotations/&assembly=Operophtera_brumata_Obru1&view=plot&altView=table

The actual path is http://localhost:8882/html/codon-usage/codon-usage.html?path=/v1/json/annotations/&assembly=Operophtera_brumata_Obru1

Not sure of the exact fix for this. We will eventually have this outward facing so not sure if its just because its being viewed through local host. For us it is looking to /var/www/ rather than /var/www/html
www/also contains v1 and cgi-bin (which of course is a security risk with executable in it).

Thanks again for all your development.

**Comment by rjchallis** [comment]
The URLs/paths for the assembly stats and codon usage plots are set in `conf/ini-files/DEFAULTS.ini`, either in the [gh-ensembl-plugin](https://github.com/genomehubs/gh-ensembl-plugin) or your fork of the [template-plugin](https://github.com/genomehubs/template-plugin) with the variables `ASSEMBLY_STATS_URL` and `CODON_USAGE_URL`. I checked both of these and they were pointing to `localhost:8882` so I'm guessing that you may be using a plugin forked before I updated this over the last few weeks. If you make changes to this file in your plugin it should be pulled in if you `docker rm -f genomehubs-ensembl` then repeat the `docker run ...` command.

Thanks for pointing out that I had the downloads server set to serve files out of `/var/www/` instead of `/var/www/html`. I've updated this container to serve files out of `/var/www/html` - you can get the latest version with `docker pull genomehubs:19.05`. This meant moving the assembly stats and codon usage files to a `utils` subdirectory so I've updated the default paths in the plugins mentioned above.

Hope this works for you now. If you do find yourself wanting to change other aspects of the download site/hosting you can mount a new `lighttpd.conf` or h5ai `options.json` file by placing them in the `download/conf` directory before running the container and these will be used in place of the defaults.
